import type { ChargingStatus, ServiceStatus, VehicleStatus } from "@prisma/client";

import type {
  NearbyChargingSite,
  VehicleDataProvider,
  VehicleSnapshotData,
} from "./types";

type MockVehicleSeed = {
  plateNumber: string;
  model: string;
  year: number;
  oemVehicleId: string;
  latitude: number;
  longitude: number;
  batteryPercent: number;
  rangeKm: number;
  ignitionOn: boolean;
  status: VehicleStatus;
  chargingStatus: ChargingStatus;
  odometerKm: number;
  locked: boolean;
  doorsOpen: boolean;
  windowsOpen: boolean;
  insideTempC: number;
  outsideTempC: number;
  climateOn: boolean;
  tpmsFrontLeft: number;
  tpmsFrontRight: number;
  tpmsRearLeft: number;
  tpmsRearRight: number;
  sentryMode: boolean;
  serviceStatus: ServiceStatus;
  softwareVersion: string;
  nearbyChargingSites: NearbyChargingSite[];
};

const BASE_VEHICLES: MockVehicleSeed[] = [
  {
    plateNumber: "12가3456",
    model: "Tesla Model 3",
    year: 2023,
    oemVehicleId: "tesla-mock-001",
    latitude: 37.5665,
    longitude: 126.978,
    batteryPercent: 82,
    rangeKm: 410,
    ignitionOn: true,
    status: "ONLINE",
    chargingStatus: "DISCONNECTED",
    odometerKm: 28450,
    locked: true,
    doorsOpen: false,
    windowsOpen: false,
    insideTempC: 22,
    outsideTempC: 18,
    climateOn: true,
    tpmsFrontLeft: 42,
    tpmsFrontRight: 42,
    tpmsRearLeft: 41,
    tpmsRearRight: 41,
    sentryMode: false,
    serviceStatus: "OK",
    softwareVersion: "2024.44.25",
    nearbyChargingSites: [
      { name: "서울시청 슈퍼차저", distanceKm: 0.8 },
      { name: "명동 충전소", distanceKm: 1.2 },
    ],
  },
  {
    plateNumber: "34나7890",
    model: "Tesla Model Y",
    year: 2024,
    oemVehicleId: "tesla-mock-002",
    latitude: 37.5172,
    longitude: 127.0473,
    batteryPercent: 64,
    rangeKm: 320,
    ignitionOn: true,
    status: "ONLINE",
    chargingStatus: "CHARGING",
    odometerKm: 12300,
    locked: true,
    doorsOpen: false,
    windowsOpen: false,
    insideTempC: 24,
    outsideTempC: 19,
    climateOn: true,
    tpmsFrontLeft: 40,
    tpmsFrontRight: 40,
    tpmsRearLeft: 39,
    tpmsRearRight: 39,
    sentryMode: false,
    serviceStatus: "OK",
    softwareVersion: "2024.44.25",
    nearbyChargingSites: [{ name: "강남역 슈퍼차저", distanceKm: 0.5 }],
  },
  {
    plateNumber: "56다1122",
    model: "Tesla Model 3",
    year: 2022,
    oemVehicleId: "tesla-mock-003",
    latitude: 37.5796,
    longitude: 126.977,
    batteryPercent: 41,
    rangeKm: 210,
    ignitionOn: false,
    status: "WARNING",
    chargingStatus: "STOPPED",
    odometerKm: 45200,
    locked: true,
    doorsOpen: false,
    windowsOpen: false,
    insideTempC: 20,
    outsideTempC: 17,
    climateOn: false,
    tpmsFrontLeft: 38,
    tpmsFrontRight: 38,
    tpmsRearLeft: 37,
    tpmsRearRight: 37,
    sentryMode: true,
    serviceStatus: "DUE_SOON",
    softwareVersion: "2024.38.12",
    nearbyChargingSites: [{ name: "경복궁 충전소", distanceKm: 1.5 }],
  },
  {
    plateNumber: "78라3344",
    model: "Tesla Model Y",
    year: 2023,
    oemVehicleId: "tesla-mock-004",
    latitude: 37.5512,
    longitude: 126.9882,
    batteryPercent: 18,
    rangeKm: 85,
    ignitionOn: false,
    status: "ALERT",
    chargingStatus: "DISCONNECTED",
    odometerKm: 38700,
    locked: true,
    doorsOpen: false,
    windowsOpen: false,
    insideTempC: 15,
    outsideTempC: 14,
    climateOn: false,
    tpmsFrontLeft: 32,
    tpmsFrontRight: 42,
    tpmsRearLeft: 40,
    tpmsRearRight: 40,
    sentryMode: true,
    serviceStatus: "OK",
    softwareVersion: "2024.44.25",
    nearbyChargingSites: [
      { name: "남산타워 슈퍼차저", distanceKm: 2.1 },
      { name: "충무로 충전소", distanceKm: 2.8 },
    ],
  },
  {
    plateNumber: "90마5566",
    model: "Tesla Model 3",
    year: 2021,
    oemVehicleId: "tesla-mock-005",
    latitude: 37.4979,
    longitude: 127.0276,
    batteryPercent: 55,
    rangeKm: 280,
    ignitionOn: false,
    status: "OFFLINE",
    chargingStatus: "COMPLETE",
    odometerKm: 62100,
    locked: true,
    doorsOpen: false,
    windowsOpen: false,
    insideTempC: 18,
    outsideTempC: 16,
    climateOn: false,
    tpmsFrontLeft: 41,
    tpmsFrontRight: 41,
    tpmsRearLeft: 40,
    tpmsRearRight: 40,
    sentryMode: false,
    serviceStatus: "OK",
    softwareVersion: "2024.26.8",
    nearbyChargingSites: [{ name: "강남구청 충전소", distanceKm: 0.9 }],
  },
  {
    plateNumber: "11바7788",
    model: "Tesla Model Y",
    year: 2024,
    oemVehicleId: "tesla-mock-006",
    latitude: 37.5407,
    longitude: 127.0692,
    batteryPercent: 73,
    rangeKm: 360,
    ignitionOn: true,
    status: "ONLINE",
    chargingStatus: "CHARGING",
    odometerKm: 8900,
    locked: true,
    doorsOpen: false,
    windowsOpen: false,
    insideTempC: 23,
    outsideTempC: 18,
    climateOn: true,
    tpmsFrontLeft: 42,
    tpmsFrontRight: 42,
    tpmsRearLeft: 41,
    tpmsRearRight: 41,
    sentryMode: false,
    serviceStatus: "OK",
    softwareVersion: "2024.44.25",
    nearbyChargingSites: [{ name: "잠실 롯데타워 슈퍼차저", distanceKm: 0.3 }],
  },
  {
    plateNumber: "22사9900",
    model: "Tesla Model 3",
    year: 2023,
    oemVehicleId: "tesla-mock-007",
    latitude: 37.4842,
    longitude: 127.0345,
    batteryPercent: 29,
    rangeKm: 150,
    ignitionOn: false,
    status: "WARNING",
    chargingStatus: "DISCONNECTED",
    odometerKm: 31500,
    locked: false,
    doorsOpen: true,
    windowsOpen: false,
    insideTempC: 19,
    outsideTempC: 17,
    climateOn: false,
    tpmsFrontLeft: 39,
    tpmsFrontRight: 39,
    tpmsRearLeft: 38,
    tpmsRearRight: 38,
    sentryMode: false,
    serviceStatus: "OK",
    softwareVersion: "2024.44.25",
    nearbyChargingSites: [{ name: "서초역 충전소", distanceKm: 1.1 }],
  },
  {
    plateNumber: "33아1357",
    model: "Tesla Model Y",
    year: 2022,
    oemVehicleId: "tesla-mock-008",
    latitude: 37.5799,
    longitude: 126.8912,
    batteryPercent: 91,
    rangeKm: 455,
    ignitionOn: true,
    status: "ONLINE",
    chargingStatus: "COMPLETE",
    odometerKm: 19800,
    locked: true,
    doorsOpen: false,
    windowsOpen: false,
    insideTempC: 22,
    outsideTempC: 17,
    climateOn: true,
    tpmsFrontLeft: 42,
    tpmsFrontRight: 42,
    tpmsRearLeft: 41,
    tpmsRearRight: 41,
    sentryMode: false,
    serviceStatus: "OK",
    softwareVersion: "2024.44.25",
    nearbyChargingSites: [{ name: "마곡 슈퍼차저", distanceKm: 1.4 }],
  },
  {
    plateNumber: "44자2468",
    model: "Tesla Model 3",
    year: 2024,
    oemVehicleId: "tesla-mock-009",
    latitude: 37.4563,
    longitude: 126.7052,
    batteryPercent: 12,
    rangeKm: 55,
    ignitionOn: false,
    status: "ALERT",
    chargingStatus: "DISCONNECTED",
    odometerKm: 5200,
    locked: true,
    doorsOpen: false,
    windowsOpen: true,
    insideTempC: 16,
    outsideTempC: 15,
    climateOn: false,
    tpmsFrontLeft: 28,
    tpmsFrontRight: 42,
    tpmsRearLeft: 40,
    tpmsRearRight: 40,
    sentryMode: true,
    serviceStatus: "IN_SERVICE",
    softwareVersion: "2024.44.25",
    nearbyChargingSites: [{ name: "인천공항 슈퍼차저", distanceKm: 3.2 }],
  },
  {
    plateNumber: "55차3579",
    model: "Tesla Model Y",
    year: 2023,
    oemVehicleId: "tesla-mock-010",
    latitude: 37.3947,
    longitude: 127.1112,
    batteryPercent: 48,
    rangeKm: 245,
    ignitionOn: false,
    status: "OFFLINE",
    chargingStatus: "DISCONNECTED",
    odometerKm: 27600,
    locked: true,
    doorsOpen: false,
    windowsOpen: false,
    insideTempC: 17,
    outsideTempC: 16,
    climateOn: false,
    tpmsFrontLeft: 40,
    tpmsFrontRight: 40,
    tpmsRearLeft: 39,
    tpmsRearRight: 39,
    sentryMode: false,
    serviceStatus: "OK",
    softwareVersion: "2024.38.12",
    nearbyChargingSites: [{ name: "판교 테크노밸리 충전소", distanceKm: 0.7 }],
  },
  {
    plateNumber: "66카4680",
    model: "Tesla Model 3",
    year: 2022,
    oemVehicleId: "tesla-mock-011",
    latitude: 37.3595,
    longitude: 127.1052,
    batteryPercent: 67,
    rangeKm: 330,
    ignitionOn: true,
    status: "ONLINE",
    chargingStatus: "CHARGING",
    odometerKm: 41200,
    locked: true,
    doorsOpen: false,
    windowsOpen: false,
    insideTempC: 21,
    outsideTempC: 18,
    climateOn: true,
    tpmsFrontLeft: 41,
    tpmsFrontRight: 41,
    tpmsRearLeft: 40,
    tpmsRearRight: 40,
    sentryMode: false,
    serviceStatus: "OK",
    softwareVersion: "2024.44.25",
    nearbyChargingSites: [{ name: "수원역 슈퍼차저", distanceKm: 0.6 }],
  },
  {
    plateNumber: "77타5791",
    model: "Tesla Model Y",
    year: 2021,
    oemVehicleId: "tesla-mock-012",
    latitude: 37.3219,
    longitude: 127.1267,
    batteryPercent: 22,
    rangeKm: 120,
    ignitionOn: false,
    status: "WARNING",
    chargingStatus: "STOPPED",
    odometerKm: 55800,
    locked: true,
    doorsOpen: false,
    windowsOpen: false,
    insideTempC: 18,
    outsideTempC: 16,
    climateOn: false,
    tpmsFrontLeft: 36,
    tpmsFrontRight: 36,
    tpmsRearLeft: 35,
    tpmsRearRight: 35,
    sentryMode: true,
    serviceStatus: "DUE_SOON",
    softwareVersion: "2024.26.8",
    nearbyChargingSites: [{ name: "용인 에버랜드 충전소", distanceKm: 4.5 }],
  },
];

function withJitter(value: number, range: number) {
  return value + (Math.random() - 0.5) * range;
}

function toSnapshot(vehicle: MockVehicleSeed): VehicleSnapshotData {
  const now = new Date();

  return {
    plateNumber: vehicle.plateNumber,
    model: vehicle.model,
    year: vehicle.year,
    oemVehicleId: vehicle.oemVehicleId,
    latitude: withJitter(vehicle.latitude, 0.01),
    longitude: withJitter(vehicle.longitude, 0.01),
    batteryPercent: Math.max(5, withJitter(vehicle.batteryPercent, 2)),
    rangeKm: Math.max(20, withJitter(vehicle.rangeKm, 15)),
    ignitionOn: vehicle.ignitionOn,
    status: vehicle.status,
    chargingStatus: vehicle.chargingStatus,
    odometerKm: vehicle.odometerKm,
    chargeLimitSoc: null,
    chargerPowerKw: null,
    shiftState: null,
    locked: vehicle.locked,
    doorsOpen: vehicle.doorsOpen,
    windowsOpen: vehicle.windowsOpen,
    doorDfOpen: vehicle.doorsOpen ? true : false,
    doorDrOpen: false,
    doorPfOpen: false,
    doorPrOpen: false,
    frontTrunkOpen: false,
    rearTrunkOpen: false,
    insideTempC: vehicle.insideTempC,
    outsideTempC: vehicle.outsideTempC,
    climateOn: vehicle.climateOn,
    tpmsFrontLeft: vehicle.tpmsFrontLeft,
    tpmsFrontRight: vehicle.tpmsFrontRight,
    tpmsRearLeft: vehicle.tpmsRearLeft,
    tpmsRearRight: vehicle.tpmsRearRight,
    sentryMode: vehicle.sentryMode,
    serviceStatus: vehicle.serviceStatus,
    softwareVersion: vehicle.softwareVersion,
    nearbyChargingSites: vehicle.nearbyChargingSites,
    lastUpdatedAt: now,
  };
}

export class MockVehicleProvider implements VehicleDataProvider {
  readonly name = "mock";

  async fetchVehicles(): Promise<VehicleSnapshotData[]> {
    return BASE_VEHICLES.map(toSnapshot);
  }

  async fetchVehicleDetail(
    plateNumber: string,
  ): Promise<VehicleSnapshotData | null> {
    const vehicle = BASE_VEHICLES.find((item) => item.plateNumber === plateNumber);
    return vehicle ? toSnapshot(vehicle) : null;
  }
}

export function getMockVehicleEvents() {
  return [
    {
      plateNumber: "78라3344",
      type: "ALERT" as const,
      message: "배터리 잔량 20% 미만",
      occurredAt: new Date(),
    },
    {
      plateNumber: "78라3344",
      type: "WARNING" as const,
      message: "타이어 공기압 이상 (전좌 32 PSI)",
      occurredAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
    {
      plateNumber: "90마5566",
      type: "OFFLINE" as const,
      message: "7일 이상 미운행",
      occurredAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    },
    {
      plateNumber: "56다1122",
      type: "WARNING" as const,
      message: "배터리 충전 권장",
      occurredAt: new Date(),
    },
    {
      plateNumber: "44자2468",
      type: "ALERT" as const,
      message: "배터리 잔량 15% 미만 — 즉시 충전 필요",
      occurredAt: new Date(),
    },
    {
      plateNumber: "44자2468",
      type: "WARNING" as const,
      message: "창문 개방 상태 감지",
      occurredAt: new Date(Date.now() - 30 * 60 * 1000),
    },
    {
      plateNumber: "22사9900",
      type: "WARNING" as const,
      message: "차량 문 개방 상태",
      occurredAt: new Date(Date.now() - 15 * 60 * 1000),
    },
    {
      plateNumber: "77타5791",
      type: "WARNING" as const,
      message: "정비 점검 예정 (30일 이내)",
      occurredAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
    {
      plateNumber: "56다1122",
      type: "ALERT" as const,
      message: "센트리 모드 이벤트 감지",
      occurredAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    },
  ];
}
