const DEFAULT_TELEMETRY_FIELDS: Record<string, { interval_seconds: number }> = {
  Location: { interval_seconds: 60 },
  GpsHeading: { interval_seconds: 60 },
  Soc: { interval_seconds: 60 },
  EstBatteryRange: { interval_seconds: 120 },
  Gear: { interval_seconds: 60 },
  VehicleSpeed: { interval_seconds: 30 },
  ChargeState: { interval_seconds: 60 },
  DetailedChargeState: { interval_seconds: 60 },
  TimeToFullCharge: { interval_seconds: 60 },
  ChargeLimitSoc: { interval_seconds: 120 },
  ACChargingPower: { interval_seconds: 60 },
  DCChargingPower: { interval_seconds: 60 },
  ChargeAmps: { interval_seconds: 60 },
  ChargePortDoorOpen: { interval_seconds: 60 },
  ChargePortLatch: { interval_seconds: 120 },
  FastChargerPresent: { interval_seconds: 120 },
  Locked: { interval_seconds: 60 },
  SentryMode: { interval_seconds: 60 },
  ValetModeEnabled: { interval_seconds: 120 },
  ServiceMode: { interval_seconds: 120 },
  Odometer: { interval_seconds: 60 },
  InsideTemp: { interval_seconds: 60 },
  OutsideTemp: { interval_seconds: 60 },
  HvacPower: { interval_seconds: 60 },
  PreconditioningEnabled: { interval_seconds: 120 },
  DoorState: { interval_seconds: 60 },
  FdWindow: { interval_seconds: 60 },
  FpWindow: { interval_seconds: 60 },
  RdWindow: { interval_seconds: 60 },
  RpWindow: { interval_seconds: 60 },
  TpmsPressureFl: { interval_seconds: 300 },
  TpmsPressureFr: { interval_seconds: 300 },
  TpmsPressureRl: { interval_seconds: 300 },
  TpmsPressureRr: { interval_seconds: 300 },
  TpmsHardWarnings: { interval_seconds: 60 },
  TpmsSoftWarnings: { interval_seconds: 120 },
  DestinationName: { interval_seconds: 60 },
  DestinationLocation: { interval_seconds: 60 },
  MinutesToArrival: { interval_seconds: 60 },
  MilesToArrival: { interval_seconds: 120 },
  ExpectedEnergyPercentAtTripArrival: { interval_seconds: 120 },
  SoftwareUpdateDownloadPercentComplete: { interval_seconds: 300 },
  SoftwareUpdateInstallationPercentComplete: { interval_seconds: 300 },
  SoftwareUpdateVersion: { interval_seconds: 600 },
};

/** CAF §4 — create SoT (Version 제외 · REST-1) */
export function getDefaultTelemetryFields() {
  return DEFAULT_TELEMETRY_FIELDS;
}
